/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PC_M1.H
**     Project   : DSPC51
**     Processor : 56F8037
**     Beantype  : PC_Master
**     Version   : Bean 01.032, Driver 01.13, CPU db: 2.87.237
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011-2-23, 下午 01:51
**     Abstract  :
**          The PC master software application is a software tool initially created
**          for developers of Motor Control applications but it may be extended to any
**          application development. This tool allows control of an application remotely
**          from a user-friendly graphical environment running on a PC.
**     Comment   :
**         8030
**     Settings  :
**          AsynchroSerial                       : Inhr7
**
**          Initialization:
**              Recorder buffer length           : 512
**              Command buffer length            : 4
**              Data buffer size                 : 128
**              Recorder timebase                : 32816
**              Board firmware major number      : 5
**              Board firmware minor number      : 0
**              Device identification string     : PC Master communication !
**     Contents  :
**         pcmasterdrvInit     - Word16 PC_M1_pcmasterdrvInit(sPCMasterComm *p_sPCMasterComm);
**         pcmasterdrvIsr      - void PC_M1_pcmasterdrvIsr(void);
**         pcmasterdrvRecorder - void PC_M1_pcmasterdrvRecorder(void);
**
**     (c) Freescale Semiconductor
**     2004 All Rights Reserved
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __PC_M1
#define __PC_M1

#include "stm32f4xx.h"
void pcmaster_recordtask_create(char priority);
void freemaster_txapi(const char *buffer, int size);

/**
* @brief 本函数为Record功能的执行函数,其需要在程序中的运行频率最快的函数中调用
* 以保证能记录到每次运行的数据.
*
* @param 
*
* @return 
*/
void PC_M1_pcmasterdrvRecorder(void);

/**
* @brief 批量数据分析,将接收到的数据送入freemaster协议分析程序
*
* @param pAddress 接收到的数据存放指针地址
* @param offset 需要处理的数据在指针地址中的偏移量
* @param length 数据长度
*
* @return 无
*/
void PutData(const char * pAddress, short offset, short length);
/**
* @brief 单个数据分析,将接收到的数据送入freemaster协议分析程序
*
* @param rxChar 接收到的数据/字符
*
* @return 无
*/
void PutChar(char rxChar);
/**
* @brief 串口等发送函数接口绑定,当freemaster协议解析数据需要返回数据时,调用
* 响应的接口函数发送数据.
*
* @param print为发送函数指针 
* void printf(const char *buffer, rt_size_t size)
*
* @return 无
*/
void SetTxApi(void *print);

/**
* @brief 模块初始化
*
* @param 无
*
* @return 无
*/
void PC_M1_PE_Init(void);

#endif /* ifndef __PC_M1 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.98 [03.79]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
